name: GEX Data Sync

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour. Adjust as needed.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests yfinance
          playwright install chromium

      - name: Run Data Scraper
        env:
          WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
        run: python main.py
